# Generated by Django 5.0.14 on 2026-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_heure', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('complet', 'Complet'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='confirme', max_length=20)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
            },
        ),
    ]
