# Generated by Django 5.0.14 on 2026-03-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendervous', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_crees', to='users.medecin'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='rendervous.creneau'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='users.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together={('patient', 'creneau')},
        ),
    ]
